## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Tue Apr 01 16:13:52 EEST 2025
android.builtInKotlin=true
# Removed deprecated/removed buildfeatures properties to fix AGP 9.0 build issue
# android.defaults.buildfeatures.buildconfig=true
# android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.dependency.excludeLibraryComponentsFromConstraints=true
android.enableJetifier=true
android.newDsl=true
android.nonFinalResIds=false
android.r8.strictFullModeForKeepRules=false
android.useAndroidX=true
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE